[package]
name = "command-block"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
#nix = { version = "0.27", features = ["ptmx"] }

